#!/usr/bin/env bash
#
# AllowanceKit CDP canary wizard — sets up CDP credentials + Base Sepolia wallet,
# then runs the canary to prove end-to-end settlement works.
#
# Generated by the /wizard skill.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — identical across every wizard. Do not hand-edit.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

TOTAL_STAGES=0
_TOTAL_MINUTES=0
_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()

_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

say()  { printf '  %s\n' "$1"; }
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

pause() { printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"; read -r _ || true; }

confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} )) && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  printf '\n  %sTo run the canary:%s\n' "$BOLD" "$RESET"
  printf '    %snode --env-file=.env scripts/canary.ts%s\n' "$DIM" "$RESET"
  printf '    %snode --env-file=.env scripts/canary.ts --full%s  # end-to-end (needs funded wallet)\n\n' "$DIM" "$RESET"
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=3
TOTAL_MINUTES=8

banner "AllowanceKit CDP canary — prove real settlement works"

# ── Stage 1: CDP API key ─────────────────────────────────────────────────
stage "Coinbase Developer Platform — API key" 4
say "We need an ECDSA (P-256) API key from the CDP portal."
say "  ${RED}Important:${RST} select ${BOLD}ECDSA${RST} as the algorithm — Ed25519 won't work for x402."
say ""
open_url "https://portal.cdp.coinbase.com"
step "Log in (create a free account if needed)."
step "In the left sidebar, click 'Secret API Keys' (or visit /api-keys/secret)."
step "Click 'Create API key'."
step "Name it (e.g. 'allowance-canary')."
step "Under 'Signature algorithm', select ${BOLD}ECDSA${RST} (NOT Ed25519)."
step "Do NOT check the Non-custodial wallet boxes — we don't need those."
step "On success, you'll see the key ID and can download/view the private key PEM."
step "Copy the API key ID (looks like 'organizations/.../apiKeys/...' or a UUID)."
ask CDP_API_KEY_ID "Paste the full API key ID:"
step "Open the downloaded key file (or copy the private key PEM from the modal)."
step "Paste it below — the full block from -----BEGIN EC PRIVATE KEY----- to -----END EC PRIVATE KEY-----."
ask_secret CDP_API_KEY_SECRET "Paste the EC private key PEM:"
write_env CDP_API_KEY_ID "$CDP_API_KEY_ID"
write_env CDP_API_KEY_SECRET "$CDP_API_KEY_SECRET"

# ── Stage 2: Base Sepolia wallet ─────────────────────────────────────────
stage "Base Sepolia wallet — fund with testnet USDC" 3
say "We need a hex private key for a Base Sepolia wallet with USDC."
say ""
say "  ${BOLD}Option A — existing wallet:${RST}  paste your hex private key below."
say "  ${BOLD}Option B — fresh wallet:${RST}     press Enter; the canary will generate one."
ask AGENT_PRIVATE_KEY "Paste hex private key (or Enter to skip for now):"

if [[ -z "$AGENT_PRIVATE_KEY" ]]; then
  # Generate a fresh keypair and show it
  AGENT_PRIVATE_KEY=$(node -e "
    const c = require('crypto');
    const pk = c.randomBytes(32).toString('hex');
    console.log(pk);
  " 2>/dev/null || echo "")
  if [[ -n "$AGENT_PRIVATE_KEY" ]]; then
    # Derive the real EVM address (keccak256 of the uncompressed pubkey) via
    # viem. sha256 of the private key is NOT an address — funding it burns funds.
    AGENT_ADDRESS=$(node -e "
      import('viem/accounts')
        .then(({ privateKeyToAccount }) => console.log(privateKeyToAccount('0x${AGENT_PRIVATE_KEY}').address))
        .catch(() => console.log('unknown'));
    " 2>/dev/null || echo "unknown")
    say "  Fresh wallet generated:"
    say "    address  ${BOLD}${AGENT_ADDRESS}${RESET}"
    say "    key      ${DIM}${AGENT_PRIVATE_KEY:0:8}…${RESET}"
    if [[ "$AGENT_ADDRESS" == "unknown" ]]; then
      warn "Could not derive the address — install viem (npm i viem), then re-run to see it."
    else
      warn "This wallet is EMPTY. Fund it at the faucets below before running the canary."
    fi
  fi
fi
write_env AGENT_PRIVATE_KEY "$AGENT_PRIVATE_KEY"

say ""
step "Fund the wallet with Base Sepolia USDC:"
open_url "https://faucet.circle.com"
say "       Select ${BOLD}Base Sepolia${RST} in the network dropdown, paste your address."
say "       No login required · 20 USDC per address every 2 hours."
say "       Fallback: https://www.coinbase.com/developer-platform/products/faucet"
say ""
say "    ${BOLD}Minimum:${RST} 0.01 USDC. ${BOLD}No testnet ETH required.${RST}"
say "    ${DIM}The wallet only signs the EIP-3009 authorization off-chain; the${RESET}"
say "    ${DIM}facilitator submits the transfer on-chain and pays the gas itself.${RESET}"
pause "Funded? Press Enter when ready."

# ── Stage 3: Run the canary ──────────────────────────────────────────────
stage "Canary — verify it works" 1
say "Running the canary against the real CDP API on Base Sepolia…"
say ""
note "  node --env-file=.env scripts/canary.ts --full"
say ""

if confirm "Run the canary now?"; then
  node --env-file=.env scripts/canary.ts --full
  pause ""
else
  say "  Run it manually later:"
  say "    ${BOLD}node --env-file=.env scripts/canary.ts --full${RST}"
  pause ""
fi

finish
